name: flutter_iconsax
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/PersianFlutter/flutter_iconsax

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: FlutterIconsax
      fonts:
        - asset: fonts/FlutterIconsax.ttf